### ISSUE TITLE
Cannot setup server

### ISSUE THREAD

**Issue by tasos12** [minnojs/minno-server#2]
Hello guys
I tried setting up the server as the manual describes and using the installation.sh but it fails
Here's the log:
**_### In file included from ../src/create_string.cpp:1:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
../src/create_string.cpp: In function ‘char* create_string(Nan::MaybeLocal<v8::Value>)’:
../src/create_string.cpp:17:37: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>&)’
   v8::String::Utf8Value string(value);
                                     ^
In file included from /home/monk/Downloads/minno-server-master/node_modules/node-sass/.node-gyp/13.13.0/include/node/node.h:67,
                 from ../../nan/nan.h:54,
                 from ../src/create_string.cpp:1:
/home/monk/Downloads/minno-server-master/node_modules/node-sass/.node-gyp/13.13.0/include/node/v8.h:3180:5: note: candidate: ‘v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)’
     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
     ^~~~~~~~~
/home/monk/Downloads/minno-server-master/node_modules/node-sass/.node-gyp/13.13.0/include/node/v8.h:3180:5: note:   candidate expects 2 arguments, 1 provided
make: *** [binding.target.mk:131: Release/obj.target/binding/src/create_string.o] Error 1
make: Leaving directory '/home/monk/Downloads/minno-server-master/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/monk/Downloads/minno-server-master/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.0-8-amd64
gyp ERR! command "/usr/local/bin/node" "/home/monk/Downloads/minno-server-master/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/monk/Downloads/minno-server-master/node_modules/node-sass
gyp ERR! node -v v13.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-16T11_45_23_517Z-debug.log_**

I tried in both linux debian and windows but none seem to work

**Comment by ronenno1** [comment]
Hi,
it seems to me that there is a problem to install the dashboard dependencies (specifically the SASS one), so I'm not entirely sure if it something about the installation itself.
In general installation.sh is a batch script that install all the relevant dependencies and services for the dashboard. 
You can find more details about the ubuntu / debian installation here:
https://docs.google.com/document/d/1ZbobgBbhOvoREsod0ms4BYWDsafiIQozZJBDmKfptYI/edit?usp=sharing
By the way it seems that sometimes there is an issue with the installation of node-sass. we will try to solve it in our end, but meanwhile you can try to use `sudo npm install --unsafe-perm node-sass` as it has suggested [here](https://askubuntu.com/questions/1062626/how-to-install-node-sass-on-ubuntu-18-04-and-how-to-succesfully-compile-scss-f) to solve this specific issue.

Please let me know if it helps you, or if you need more help / clarifications.

Ronen
